name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build services
      run: docker compose build
    
    - name: Run integration tests
      run: docker compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test

    - name: Shutdown services
      if: always()
      run: docker compose -f docker-compose.yaml -f docker-compose.test.yaml down
